version: '3'
services:

  config-server:
    container_name: mycar-config-server
    image: mycar/config-server:latest
    ports:
      - "9090:9090"

  eureka-server:
    container_name: mycar-eureka-server
    image: mycar/eureka-server:latest
    ports:
      - "9091:9091"
    depends_on:
      - config-server
    restart: always

  zuul-server:
    container_name: mycar-zuul-server
    image: mycar/zuul-server:latest
    ports:
      - "9092:9092"
    depends_on:
      - eureka-server
      - config-server
    restart: always

  auth-server:
    container_name: mycar-auth-server
    image: mycar/auth-server:latest
    ports:
      - "9093:9093"
    depends_on:
      - eureka-server
      - config-server
    restart: always

  map-service:
    container_name: mycar-map-service
    image: mycar/map-service:latest
    ports:
      - "8082-8082"
    depends_on:
      - config-server
      - eureka-server
    restart: always

  account-service:
    container_name: mycar-account-service
    image: mycar/account-service:latest
    ports:
      - "8083-8083"
    depends_on:
      - config-server
      - eureka-server
    restart: always

  notification-service:
    container_name: mycar-notification-service
    image: mycar/notification-service:latest
    ports:
      - "8084-8084"
    depends_on:
      - config-server
      - eureka-server
    restart: always

  technical-examination-service:
    container_name: mycar-technical-examination-service
    image: mycar/technical-examination-service:latest
    ports:
      - "8085-8085"
    depends_on:
      - config-server
      - eureka-server
    restart: always

  car-manage-service:
    container_name: mycar-car-manage-service
    image: mycar/car-service:latest
    ports:
      - "8086-8086"
    depends_on:
      - config-server
      - eureka-server
    restart: always

  insurance-service:
    container_name: mycar-insurance-service
    image: mycar/insurance-service:latest
    ports:
      - "8087-8087"
    depends_on:
      - config-server
      - eureka-server
    restart: always

  turbine-service:
    container_name: mycar-turbine-service
    image: mycar/turbine-service:latest
    ports:
      - "9094-9094"
    depends_on:
      - config-server
      - eureka-server
      - notification-service
      - technical-examination-service
      - insurance-service
    restart: always

  db-postgres-account-service:
    container_name: postgres-account
    image: postgres:latest
    environment:
      - POSTGRES_USER=account-db-user
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=account-service-db
    volumes:
      - postgres-account-data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5000:5432"

  db-postgres-map-service:
    container_name: postgres-map
    image: postgres:latest
    environment:
      - POSTGRES_USER=map-db-user
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=map-service-db
    volumes:
      - postgres-map-data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5001:5432"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  db-postgres-notification-service:
    container_name: postgres-notification
    image: postgres:latest
    environment:
      - POSTGRES_USER=notification-db-user
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=notification-service-db
    volumes:
      - postgres-notification-data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5002:5432"

  db-postgres-technical-examination-service:
    container_name: postgres-technical-examination
    image: postgres:latest
    environment:
      - POSTGRES_USER=technical-examination-db-user
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=technical-examination-service-db
    volumes:
      - postgres-technical-examination-data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5003:5432"

  db-postgres-car-service:
    container_name: postgres-car
    image: postgres:latest
    environment:
      - POSTGRES_USER=car-db-user
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=car-service-db
    volumes:
      - postgres-car-data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5004:5432"

  db-postgres-insurance-service:
    container_name: postgres-insurance
    image: postgres:latest
    environment:
      - POSTGRES_USER=insurance-db-user
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=insurance-service-db
    volumes:
      - postgres-insurance-data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5005:5432"

volumes:
  postgres-account-data:
  postgres-map-data:
  postgres-notification-data:
  postgres-technical-examination-data:
  postgres-car-data:
  postgres-insurance-data: